### ISSUE TITLE
Issue with ScanditBarcode/ScanditBarcodeScanner.h file not found

### ISSUE THREAD

**Issue by mrpotatodip** [salathegroup/react-native-scandit#2]
I would like to seek assistance with regards to this issue after I followed the instruction on how to create and use the library.

"ScanditBarcode/ScanditBarcodeScanner.h file not found"

this error occured under SBSScanSettings+Helpers.h

Thanks a lot.

Cheers!

**Comment by Boris-c** [comment]
Hi Jayson,

It seems Xcode can't find the Scandit library. Did you follow the 4 steps in "Add Scandit SDK" for iOS?

Scandit's SDK can be downloaded from https://ssl.scandit.com/sdk (a Scandit account is required).

Boris

**Comment by D1no** [comment]
@Boris-c 
We have build a very basic scandit bridge for android and ios and I am looking to replace it with this one. However, adding the library to our working scandit app, or to a new app, lets `SBScanSettings+Helps.h` throw a `'ScanditBarcodeScanner/ScanditBarcodeScanner.h' file not found` during compilation.

Without your library, our scandit app works without a problem.

Looking into your `SGScandit.xcodeproj` it seems you have hardcoded the framework search path to `/Users/BDC/Downloads/scandit-barcodescanner-community-ios_5.3.0BETA2/ScanditSDK` 🚨

![screen shot 2017-07-13 at 13 48 09](https://user-images.githubusercontent.com/2397125/28164973-0e20fcde-67d2-11e7-94c7-84126d4f689c.png)
